language: c
os:
  - linux
dist: bionic
cache:
  directories:
    - /home/travis/perl5
    - /home/travis/root
# The non-x86_64 images currently lack cpanminus, when that is fixed
# the cpanminus & universe sourceline can be removed.
addons:
  apt:
    update: false
    sources:
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe'
    packages:
      - cpanminus
      - libtool-bin
      - libapr1-dev
      - libaprutil1-dev
      - perl-doc
      - lua5.3-dev
      - libbrotli-dev
      - libcurl4-openssl-dev
      - libsystemd-dev
      - libnghttp2-dev
      - libjansson-dev
      - libpcre2-dev
env:
  global:
    - MFLAGS=-j2

# This defines two condition anchors which can be used in job
# definitions to either:
#  condition_24x_only => run the job only for 2.4.x
#  condition_not_24x  => run the job everywhere EXCEPT 2.4.x
_cond1: &condition_24x_only (branch is present AND branch = 2.4.x) OR (tag is present AND tag ~= /^2.4/)
_cond2: &condition_not_24x (branch is present AND branch != 2.4.x) OR (tag is present AND tag !~ /^2.4/)

jobs:
  include:
    - name: Linux Ubuntu, Default module set
    - if: *condition_not_24x
      name: Linux Fedora
      env: CONTAINER=fedora
           DOCKERFILE=test/travis_Dockerfile_fedora
           CONFIG="--enable-mods-shared=reallyall"
           APR_VERSION=1.7.0 APU_VERSION=1.6.1
           APU_CONFIG="--with-crypto"
    - if: *condition_not_24x
      name: Linux CentOS 7
      env: CONTAINER=centos:7
           DOCKERFILE=test/travis_Dockerfile_fedora
           CONFIG="--enable-mods-shared=reallyall"
           APR_VERSION=1.7.0 APU_VERSION=1.6.1
           APU_CONFIG="--with-crypto"
    - if: *condition_not_24x
      name: Linux CentOS 8
      env: CONTAINER=centos:8
           DOCKERFILE=test/travis_Dockerfile_centos8
           CONFIG="--enable-mods-shared=reallyall"
           APR_VERSION=1.7.0 APU_VERSION=1.6.x
           APU_CONFIG="--with-crypto"
           
# CPAN modules are to be used with the system Perl and always with
# CC=gcc, e.g. for the CC="gcc -m32" case the builds are not correct
# otherwise.
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a ! -v CONTAINER ]; then
        cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib);
        CC=gcc cpanm --notest Net::SSL LWP::Protocol::https ExtUtils::Embed Test::More AnyEvent DateTime HTTP::DAV Protocol::HTTP2::Client FCGI Apache::Test;
    fi

before_script:
  - test -v CONTAINER || ./test/travis_before_${TRAVIS_OS_NAME}.sh

script:
  - if test -v CONTAINER; then
      ./test/travis_container.sh;
    else
      ./test/travis_run_${TRAVIS_OS_NAME}.sh;
    fi

notifications:
  irc: "chat.freenode.net#httpd-dev"
  # Disabled to avoid too many failure emails to dev@,
  # some builds occasionally fail.
  #email:
  #  - dev@httpd.apache.org
