language: c
os:
  - linux
cache:
  directories:
    - /home/travis/perl5
addons:
  apt:
    packages:
      - libtool-bin
      - libapr1-dev
      - libaprutil1-dev
      - perl-doc
      - lua5.3-dev
      - libbrotli-dev
      - libcurl4-openssl-dev
      - libsystemd-dev
      - libnghttp2-dev
      - libjansson-dev

matrix:
  include:
    - name: Linux Ubuntu, Default module set
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu, Default, all-modules
      env: CONFIG="--enable-mods-shared=reallyall --enable-load-all-modules"
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu, Prefork MPM, all-modules
      env: CONFIG="--enable-mods-shared=reallyall --enable-load-all-modules --with-mpm=prefork"
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu, Worker MPM, all-modules
      env: CONFIG="--enable-mods-shared=reallyall --enable-load-all-modules --with-mpm=worker"
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu Bionic, all-modules
      os: linux
      dist: bionic
      env: CONFIG="--enable-mods-shared=reallyall --enable-load-all-modules"
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu Bionic, GCC 7 maintainer-mode w/-Werror
      os: linux
      dist: bionic
      env: CONFIG="--enable-mods-shared=reallyall --enable-load-all-modules --enable-maintainer-mode NOTEST_CFLAGS=-Werror CC=gcc-7"
           SKIP_TESTING=1
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu, GCC 8 maintainer-mode w/-Werror
      env: CONFIG="--enable-mods-shared=reallyall --enable-load-all-modules --enable-maintainer-mode NOTEST_CFLAGS=-Werror CC=gcc-8"
           SKIP_TESTING=1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - libtool-bin
            - libapr1-dev
            - libaprutil1-dev
            - perl-doc
            - lua5.3-dev
            - libbrotli-dev
            - libcurl4-openssl-dev
            - libsystemd-dev
            - libnghttp2-dev
            - libjansson-dev
    # -------------------------------------------------------------------------

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib);
        cpanm --notest Net::SSL LWP::Protocol::https ExtUtils::Embed Test::More AnyEvent DateTime HTTP::DAV Protocol::HTTP2::Client FCGI;
    fi

before_script:
  - ./test/travis_before_${TRAVIS_OS_NAME}.sh

script:
  - ./test/travis_run_${TRAVIS_OS_NAME}.sh
