language: c
os:
  - linux
dist: bionic
cache:
  directories:
    - /home/travis/perl5
    - /home/travis/root
# The non-x86_64 images currently lack cpanminus, when that is fixed
# the cpanminus & universe sourceline can be removed.
addons:
  apt:
    update: false
    sources:
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe'
    packages:
      - cpanminus
      - libtool-bin
      - libapr1-dev
      - libaprutil1-dev
      - perl-doc
      - liblua5.3-dev
      - libbrotli-dev
      - libcurl4-openssl-dev
      - libsystemd-dev
      - libnghttp2-dev
      - libjansson-dev
      - libpcre2-dev
      - libldap2-dev
      - ldap-utils
      - gdb
env:
  global:
    - MFLAGS=-j2

# This defines two condition anchors which can be used in job
# definitions to either:
#  condition_24x_only => run the job only for 2.4.x
#  condition_not_24x  => run the job everywhere EXCEPT 2.4.x
_cond1: &condition_24x_only (branch is present AND branch = 2.4.x) OR (tag is present AND tag ~= /^2.4/)
_cond2: &condition_not_24x (branch is not present OR branch != 2.4.x) AND (tag is not present OR tag !~ /^2.4/)

jobs:
  include:
    - name: Linux Ubuntu, APR 1.7.0, APR-util 1.6.1, LDAP
      env: APR_VERSION=1.7.0
           APU_VERSION=1.6.1 APU_CONFIG="--with-crypto --with-ldap"
           CONFIG="--enable-mods-shared=reallyall"
           TEST_MALLOC=1 TEST_LDAP=1 TEST_ARGS="-defines LDAP"
           TESTS="t/modules/"

# CPAN modules are to be used with the system Perl and always with
# CC=gcc, e.g. for the CC="gcc -m32" case the builds are not correct
# otherwise.
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a ! -v SKIP_TESTING ]; then
        if [ -v CLEAR_CACHE ]; then rm -rf ~/perl5; fi;
        cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib);
        CC=gcc cpanm --notest Net::SSL LWP::Protocol::https ExtUtils::Embed Test::More AnyEvent DateTime HTTP::DAV Protocol::HTTP2::Client FCGI AnyEvent::WebSocket::Client Apache::Test;
    fi

before_script:
  - ./test/travis_before_${TRAVIS_OS_NAME}.sh

script:
  - ./test/travis_run_${TRAVIS_OS_NAME}.sh

# Send notifications by default to IRC and dev@, for everything but
# forks, otherwise any build from a fork will spam the list with CI
# results.
notifications:
  irc:
    if: fork = false
    channels:
      - "chat.freenode.net#httpd-dev"
  email:
    if: fork = false
    recipients:
      - dev@httpd.apache.org
