name: Linux

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'docs/**'
      - STATUS
      - CHANGES
      - changes-entries/*
    tags:
      - 2.*
  pull_request:
    branches: [ "trunk", "2.4.x" ]
    paths-ignore:
      - 'docs/**'
      - STATUS
      - CHANGES
      - changes-entries/*

env:
  MARGS: "-j2"
  CFLAGS: "-g"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: 
          - name: OpenSSL 3.2 build
            config: --enable-mods-shared=reallyall --enable-maintainer-mode
            env: |
              TEST_OPENSSL3=3.2.1
              APR_VERSION=1.7.4
              APU_VERSION=1.6.3
              APU_CONFIG="--with-crypto"
              CLEAR_CACHE=1
          - name: OpenSSL 3.2 -Werror build
            config: --enable-mods-shared=reallyall --enable-maintainer-mode
            notest-cflags: -Werror -O2 -Wno-deprecated-declarations
            env: |
              TEST_OPENSSL3=3.2.1
              APR_VERSION=1.7.4
              APU_VERSION=1.6.3
              APU_CONFIG="--with-crypto"
              CLEAR_CACHE=1
          - name: OpenSSL 3.2 no-engine build
            config: --enable-mods-shared=reallyall --enable-maintainer-mode
            env: |
              TEST_OPENSSL3=3.2.1
              OPENSSL_CONFIG=no-engine
              APR_VERSION=1.7.4
              APU_VERSION=1.6.3
              APU_CONFIG="--with-crypto"
              CLEAR_CACHE=1
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NOTEST_CFLAGS: ${{ matrix.notest-cflags }}
      CONFIG: ${{ matrix.config }}
    name: ${{ matrix.name }}
    steps:
    - name: Set environment variables
      run: |
        echo "${{ matrix.env }}" >> $GITHUB_ENV
        echo JOBID=`echo "${{ matrix.notest-cflags }} ${{ matrix.env }} ${{ matrix.config }}'"| md5sum - | sed 's/ .*//'` >> $GITHUB_ENV
    - name: apt refresh
      run: sudo apt-get -o Acquire::Retries=5 update
    - name: Install prerequisites
      run: sudo apt-get install -o Acquire::Retries=5
                    cpanminus libtool-bin libapr1-dev libaprutil1-dev
                    liblua5.3-dev libbrotli-dev libcurl4-openssl-dev     
                    libnghttp2-dev libjansson-dev libpcre2-dev gdb
                    perl-doc ${{ matrix.pkgs }}
    - uses: actions/checkout@v3
    - name: Cache installed libraries
      uses: actions/cache@v3
      with:
        path: ~/root
        key: cache-libs-${{ env.JOBID }}
    - name: Cache CPAN modules
      uses: actions/cache@v3
      with:
        path: ~/perl5
        key: cache-cpan-${{ env.JOBID }}
    - name: Configure environment
      run: ./test/travis_before_linux.sh
      timeout-minutes: 15
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: config.log-${{ env.JOBID }}
        path: |
          /home/runner/build/**/config.log
    - name: Build and test
      run: ./test/travis_run_linux.sh
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: error_log-${{ env.JOBID }}
        path: test/perl-framework/t/logs/error_log

